version: '3.8'

services:
  text-emotion:
    build:
      context: ./ai-features/text-emotion
      dockerfile: Dockerfile
    container_name: text-emotion-service
    ports:
      - "8001:8000"
    environment:
      - SUPABASE_URL=https://ixnbfvyeniksbqcfdmdo.supabase.co
      - SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4bmJmdnllbmlrc2JxY2ZkbWRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzE0MDE3NjgsImV4cCI6MjA0Njk3Nzc2OH0.h4JtVbwtKAe38yvtOLYvZIbhmMy6v2QCVg51Q11ubYg
    volumes:
      - ./ai-features/text-emotion:/app
      - ./shared:/app/shared
    networks:
      - emotion-network

  image-emotion:
    build:
      context: ./ai-features/image-emotion
      dockerfile: Dockerfile
    container_name: image-emotion-service
    ports:
      - "8002:8000"
    environment:
      - SUPABASE_URL=https://ixnbfvyeniksbqcfdmdo.supabase.co
      - SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4bmJmdnllbmlrc2JxY2ZkbWRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzE0MDE3NjgsImV4cCI6MjA0Njk3Nzc2OH0.h4JtVbwtKAe38yvtOLYvZIbhmMy6v2QCVg51Q11ubYg
    volumes:
      - ./ai-features/image-emotion:/app
      - ./shared:/app/shared
    networks:
      - emotion-network

networks:
  emotion-network:
    driver: bridge